server:
  port: 8082

spring:
  application:
    name: account-service
  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true
  sleuth: 
    sampler:
      probability: 1.0
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: redis
    port: 6379
    password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  zipkin:
    enabled: true
    base-url: http://zipkin:9411
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus

eureka:
  client:
    service-url:
      defaultZone: http://discovery:9001/eureka