spring:
  application:
    name: customer-service
  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true
  sleuth: 
    sampler:
      probability: 1.0

account-service:
  ribbon:
    listOfServers: http://localhost:8082/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka