server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    customer-service:
      path: /customer/**
      stripPrefix: false
      serviceId: customerService
    account-service:
      path: /account/**
      stripPrefix: false
      serviceId: accountService
  SendErrorFilter:
    post:
      disable: true

ribbon:
   eureka:
      enabled: false

customerService:
  ribbon:
    listOfServers: http://customer-service:8081/
accountService:
  ribbon:
    listOfServers: http://account-service:8082/

eureka:
  client:
    service-url:
      defaultZone: http://discovery:9001/eureka
      fetch-registry: true