server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    customer-service:
      path: /customer/**
      stripPrefix: false
      serviceId: customerService
    account-service:
      path: /account/**
      stripPrefix: false
      serviceId: accountService

customerService:
  ribbon:
    listOfServices: http://localhost:8081/,http://localhost:8084/
accountService:
  ribbon:
    listOfServices: http://localhost:8081/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      fetch-registry: true