server:
  port: 8080

spring:
  application:
    name: gateway-proxy

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    customer-service:
      path: /customer/**
      url: http://localhost:8081/
      stripPrefix: false
    account-service:
      path: /account/**
      url: http://localhost:8081/
      stripPrefix: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      fetch-registry: true